#Import drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


#Prepare data

#AR: 3 Activities

In [31]:
import pandas as pd
import numpy as np
np.random.seed(2021)
!wget http://casas.wsu.edu/datasets/hh103.zip
!wget http://casas.wsu.edu/datasets/hh101.zip
!unzip '/content/hh101.zip'
!unzip /content/hh103.zip

Final_Data_S1 = pd.read_csv("/content/hh103/hh103.ann.features.csv")
Final_Data_S2 = pd.read_csv("/content/hh101/hh101.ann.features.csv")

Final_Data_S1 = Final_Data_S1.drop(['lastSensorEventHours', 'lastSensorEventSeconds', 'lastSensorDayOfWeek','lastSensorID'], axis= 1)
Final_Data_S2 = Final_Data_S2.drop(['lastSensorEventHours', 'lastSensorEventSeconds','lastSensorDayOfWeek', 'lastSensorID'], axis= 1)

Final_Data_S1 = Final_Data_S1[Final_Data_S1.activity.isin(['Cook_Breakfast',  'Watch_TV', 'Toilet' ])]
Final_Data_S2 = Final_Data_S2[Final_Data_S2.activity.isin([ 'Cook_Breakfast',  'Watch_TV', 'Toilet' ])]

Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.activity.isin(['Watch_TV'])].index,'activity']=0
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.activity.isin(['Toilet'])].index,'activity']=1
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.activity.isin(['Cook_Breakfast'])].index,'activity']=2

Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.activity.isin(['Watch_TV'])].index,'activity']=0
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.activity.isin(['Toilet'])].index,'activity']=1
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.activity.isin(['Cook_Breakfast'])].index,'activity']=2

Data_0 = Final_Data_S1[Final_Data_S1.activity == 0].iloc[:2000]#2000(#4000 for unbalanced)
Data_2 = Final_Data_S1[Final_Data_S1.activity == 1].iloc[:2000]#2000
Data_3 = Final_Data_S1[Final_Data_S1.activity == 2].iloc[:2000]#2000
frames = [Data_0, Data_2, Data_3]
Final_Data_S1 = pd.concat(frames)

Data_0 = Final_Data_S2[Final_Data_S2.activity == 0].iloc[:1000]#1000(#2000 for unbalanced)
Data_2 = Final_Data_S2[Final_Data_S2.activity == 1].iloc[:1000]#1000
Data_3 = Final_Data_S2[Final_Data_S2.activity == 2].iloc[:1000]#1000
frames = [Data_0, Data_2, Data_3]
Final_Data_S2 = pd.concat(frames)


Final_Data_S1 = Final_Data_S1.sample(frac = 1)
Final_Data_S2 = Final_Data_S2.sample(frac = 1)


Source_train = Final_Data_S1.iloc[1000:,:]#1000
Source_test = Final_Data_S1.iloc[:1000,:]

Target_train = Final_Data_S2.iloc[500:,:]#500
Target_test = Final_Data_S2.iloc[:500,:]

Source_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_train.csv', index=False)
Source_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_test.csv', index=False)
Target_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_train.csv', index=False)
Target_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_test.csv', index=False)


#AR: 5 activities

In [40]:
import pandas as pd
import numpy as np
np.random.seed(2021)
!wget http://casas.wsu.edu/datasets/hh103.zip
!wget http://casas.wsu.edu/datasets/hh101.zip
!unzip '/content/hh101.zip'
!unzip /content/hh103.zip

Final_Data_S1 = pd.read_csv("/content/hh103/hh103.ann.features.csv")
Final_Data_S2 = pd.read_csv("/content/hh101/hh101.ann.features.csv")

Final_Data_S1 = Final_Data_S1.drop(['lastSensorEventHours', 'lastSensorEventSeconds', 'lastSensorDayOfWeek','lastSensorID'], axis= 1)
Final_Data_S2 = Final_Data_S2.drop(['lastSensorEventHours', 'lastSensorEventSeconds','lastSensorDayOfWeek', 'lastSensorID'], axis= 1)

Final_Data_S1 = Final_Data_S1[Final_Data_S1.activity.isin(['Cook_Dinner', 'Cook_Breakfast', 'Cook_Lunch', 'Watch_TV', 'Toilet' ])]
Final_Data_S2 = Final_Data_S2[Final_Data_S2.activity.isin(['Cook_Dinner', 'Cook_Breakfast', 'Cook_Lunch', 'Watch_TV', 'Toilet' ])]

Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.activity.isin(['Watch_TV'])].index,'activity']=0
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.activity.isin(['Cook_Lunch'])].index,'activity']=1
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.activity.isin(['Toilet'])].index,'activity']=2
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.activity.isin(['Cook_Breakfast'])].index,'activity']=3
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.activity.isin(['Cook_Dinner'])].index,'activity']=4

Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.activity.isin(['Watch_TV'])].index,'activity']=0
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.activity.isin(['Cook_Lunch'])].index,'activity']=1
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.activity.isin(['Toilet'])].index,'activity']=2
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.activity.isin(['Cook_Breakfast'])].index,'activity']=3
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.activity.isin(['Cook_Dinner'])].index,'activity']=4

Data_0 = Final_Data_S1[Final_Data_S1.activity == 0].iloc[:2000]#2000(#4000 for unbalanced)
Data_1 = Final_Data_S1[Final_Data_S1.activity == 1].iloc[:2000]#2000
Data_2 = Final_Data_S1[Final_Data_S1.activity == 2].iloc[:2000]#2000
Data_3 = Final_Data_S1[Final_Data_S1.activity == 3].iloc[:2000]#2000
Data_4 = Final_Data_S1[Final_Data_S1.activity == 4].iloc[:2000]#2000(#4000 for unbalanced)
frames = [Data_0, Data_1, Data_2, Data_3, Data_4]
Final_Data_S1 = pd.concat(frames)

Data_0 = Final_Data_S2[Final_Data_S2.activity == 0].iloc[:1000]#1000(#2000 for unbalanced)
Data_1 = Final_Data_S2[Final_Data_S2.activity == 1].iloc[:1000]#1000
Data_2 = Final_Data_S2[Final_Data_S2.activity == 2].iloc[:1000]#1000
Data_3 = Final_Data_S2[Final_Data_S2.activity == 3].iloc[:1000]#1000
Data_4 = Final_Data_S2[Final_Data_S2.activity == 4].iloc[:1000]#1000(#2000 for unbalanced)
frames = [Data_0, Data_1, Data_2, Data_3, Data_4]
Final_Data_S2 = pd.concat(frames)


Final_Data_S1 = Final_Data_S1.sample(frac = 1)
Final_Data_S2 = Final_Data_S2.sample(frac = 1)

Source_train = Final_Data_S1.iloc[1000:,:]#1000#
Source_test = Final_Data_S1.iloc[:1000,:]

Target_train = Final_Data_S2.iloc[500:,:]#500#
Target_test = Final_Data_S2.iloc[:500,:]

Source_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_train.csv', index=False)
Source_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_test.csv', index=False)
Target_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_train.csv', index=False)
Target_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_test.csv', index=False)

#OE: 2 labels unbalanced

In [2]:
import pandas as pd
import numpy as np
np.random.seed(2021)
Final_Data_S1 = pd.read_csv("/content/drive/MyDrive/Final_Data_S1.csv")
Final_Data_S2 = pd.read_csv("/content/drive/MyDrive/Final_Data_S2.csv")

Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([3.0, 4.0])].index,'labels']=1
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([3.0, 4.0])].index,'labels']=1

!pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([0.0])].index,'labels']=0
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([1.0])].index,'labels']=1
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([2.0])].index,'labels']=1

Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([0.0])].index,'labels']=0
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([1.0])].index,'labels']=1
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([2.0])].index,'labels']=1

labels_S1 = Final_Data_S1.labels
labels_S2 = Final_Data_S2.labels
Data_S1 = Final_Data_S1.drop(['time', 'labels'], axis= 1)
Data_S2 = Final_Data_S2.drop(['time', 'labels'], axis= 1)

from sklearn.decomposition import PCA
pca = PCA(n_components=9)
principalComponents_S1 = pca.fit_transform(Data_S1)
pca = PCA(n_components=9)
principalComponents_S2 = pca.fit_transform(Data_S2)

sm = SMOTE(random_state=2)
principalComponents_S1, labels_S1 = sm.fit_resample(principalComponents_S1, labels_S1)
principalComponents_S2, labels_S2 = sm.fit_resample(principalComponents_S2, labels_S2)

Final_Data_S1 = pd.DataFrame(principalComponents_S1)
Final_Data_S2 = pd.DataFrame(principalComponents_S2)

Final_Data_S1['labels'] = labels_S1
Final_Data_S2['labels'] = labels_S2


Data_0 = Final_Data_S1[Final_Data_S1.labels == 0].iloc[:1045]
Data_2 = Final_Data_S1[Final_Data_S1.labels == 1].iloc[:300]
frames = [Data_0, Data_2]
Final_Data_S1 = pd.concat(frames)

Data_0 = Final_Data_S2[Final_Data_S2.labels == 0].iloc[:772]
Data_2 = Final_Data_S2[Final_Data_S2.labels == 1].iloc[:200]
frames = [Data_0, Data_2]
Final_Data_S2 = pd.concat(frames)

Final_Data_S1 = Final_Data_S1.sample(frac = 1)
Final_Data_S2 = Final_Data_S2.sample(frac = 1)

Source_train = Final_Data_S1.iloc[200:,:]
Source_test = Final_Data_S1.iloc[:200,:]

Target_train = Final_Data_S2.iloc[150:,:]
Target_test = Final_Data_S2.iloc[:150,:]

Source_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_train.csv', index=False)
Source_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_test.csv', index=False)
Target_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_train.csv', index=False)
Target_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_test.csv', index=False)

#OE: 3 labels unbalanced

In [16]:
import pandas as pd
import numpy as np
np.random.seed(2021)
Final_Data_S1 = pd.read_csv("/content/drive/MyDrive/Final_Data_S1.csv")
Final_Data_S2 = pd.read_csv("/content/drive/MyDrive/Final_Data_S2.csv")

Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([3.0, 4.0])].index,'labels']=2
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([3.0, 4.0])].index,'labels']=2

!pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([0.0])].index,'labels']=0
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([1.0])].index,'labels']=1
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([2.0])].index,'labels']=2

Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([0.0])].index,'labels']=0
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([1.0])].index,'labels']=1
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([2.0])].index,'labels']=2

labels_S1 = Final_Data_S1.labels
labels_S2 = Final_Data_S2.labels
Data_S1 = Final_Data_S1.drop(['time', 'labels'], axis= 1)
Data_S2 = Final_Data_S2.drop(['time', 'labels'], axis= 1)

from sklearn.decomposition import PCA
pca = PCA(n_components=9)
principalComponents_S1 = pca.fit_transform(Data_S1)
pca = PCA(n_components=9)
principalComponents_S2 = pca.fit_transform(Data_S2)

sm = SMOTE(random_state=2)
principalComponents_S1, labels_S1 = sm.fit_resample(principalComponents_S1, labels_S1)
principalComponents_S2, labels_S2 = sm.fit_resample(principalComponents_S2, labels_S2)

Final_Data_S1 = pd.DataFrame(principalComponents_S1)
Final_Data_S2 = pd.DataFrame(principalComponents_S2)

Final_Data_S1['labels'] = labels_S1
Final_Data_S2['labels'] = labels_S2


Data_0 = Final_Data_S1[Final_Data_S1.labels == 0].iloc[:1045]
Data_2 = Final_Data_S1[Final_Data_S1.labels == 1].iloc[:300]
Data_3 = Final_Data_S1[Final_Data_S1.labels == 2].iloc[:300]
frames = [Data_0, Data_2, Data_3]
Final_Data_S1 = pd.concat(frames)

Data_0 = Final_Data_S2[Final_Data_S2.labels == 0].iloc[:772]
Data_2 = Final_Data_S2[Final_Data_S2.labels == 1].iloc[:200]
Data_3 = Final_Data_S2[Final_Data_S2.labels == 2].iloc[:200]
frames = [Data_0, Data_2, Data_3]
Final_Data_S2 = pd.concat(frames)

Final_Data_S1 = Final_Data_S1.sample(frac = 1)
Final_Data_S2 = Final_Data_S2.sample(frac = 1)

Source_train = Final_Data_S1.iloc[200:,:]
Source_test = Final_Data_S1.iloc[:200,:]

Target_train = Final_Data_S2.iloc[150:,:]
Target_test = Final_Data_S2.iloc[:150,:]

Source_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_train.csv', index=False)
Source_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_test.csv', index=False)
Target_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_train.csv', index=False)
Target_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_test.csv', index=False)

#OE: 2 labels balanced

In [10]:
import pandas as pd
import numpy as np
np.random.seed(2021)
Final_Data_S1 = pd.read_csv("/content/drive/MyDrive/Final_Data_S1.csv")
Final_Data_S2 = pd.read_csv("/content/drive/MyDrive/Final_Data_S2.csv")

Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([3.0, 4.0])].index,'labels']=1
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([3.0, 4.0])].index,'labels']=1

!pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([0.0])].index,'labels']=0
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([1.0])].index,'labels']=1
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([2.0])].index,'labels']=1

Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([0.0])].index,'labels']=0
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([1.0])].index,'labels']=1
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([2.0])].index,'labels']=1

labels_S1 = Final_Data_S1.labels
labels_S2 = Final_Data_S2.labels
Data_S1 = Final_Data_S1.drop(['time', 'labels'], axis= 1)
Data_S2 = Final_Data_S2.drop(['time', 'labels'], axis= 1)

from sklearn.decomposition import PCA
pca = PCA(n_components=9)
principalComponents_S1 = pca.fit_transform(Data_S1)
pca = PCA(n_components=9)
principalComponents_S2 = pca.fit_transform(Data_S2)

sm = SMOTE(random_state=2)
principalComponents_S1, labels_S1 = sm.fit_resample(principalComponents_S1, labels_S1)
principalComponents_S2, labels_S2 = sm.fit_resample(principalComponents_S2, labels_S2)

Final_Data_S1 = pd.DataFrame(principalComponents_S1)
Final_Data_S2 = pd.DataFrame(principalComponents_S2)

Final_Data_S1['labels'] = labels_S1
Final_Data_S2['labels'] = labels_S2


Final_Data_S1 = Final_Data_S1.sample(frac = 1)
Final_Data_S2 = Final_Data_S2.sample(frac = 1)

Source_train = Final_Data_S1.iloc[500:,:]
Source_test = Final_Data_S1.iloc[:500,:]

Target_train = Final_Data_S2.iloc[500:,:]
Target_test = Final_Data_S2.iloc[:500,:]

Source_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_train.csv', index=False)
Source_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_test.csv', index=False)
Target_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_train.csv', index=False)
Target_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_test.csv', index=False)

#OE: 3 labels balanced

In [20]:
import pandas as pd
import numpy as np
np.random.seed(2021)
Final_Data_S1 = pd.read_csv("/content/drive/MyDrive/Final_Data_S1.csv")
Final_Data_S2 = pd.read_csv("/content/drive/MyDrive/Final_Data_S2.csv")


Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([3.0, 4.0])].index,'labels']=2
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([3.0, 4.0])].index,'labels']=2

!pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([0.0])].index,'labels']=0
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([1.0])].index,'labels']=1
Final_Data_S1.loc[Final_Data_S1[Final_Data_S1.labels.isin([2.0])].index,'labels']=2

Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([0.0])].index,'labels']=0
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([1.0])].index,'labels']=1
Final_Data_S2.loc[Final_Data_S2[Final_Data_S2.labels.isin([2.0])].index,'labels']=2

labels_S1 = Final_Data_S1.labels
labels_S2 = Final_Data_S2.labels
Data_S1 = Final_Data_S1.drop(['time', 'labels'], axis= 1)
Data_S2 = Final_Data_S2.drop(['time', 'labels'], axis= 1)

from sklearn.decomposition import PCA
pca = PCA(n_components=9)
principalComponents_S1 = pca.fit_transform(Data_S1)
pca = PCA(n_components=9)
principalComponents_S2 = pca.fit_transform(Data_S2)

sm = SMOTE(random_state=2)
principalComponents_S1, labels_S1 = sm.fit_resample(principalComponents_S1, labels_S1)
principalComponents_S2, labels_S2 = sm.fit_resample(principalComponents_S2, labels_S2)

Final_Data_S1 = pd.DataFrame(principalComponents_S1)
Final_Data_S2 = pd.DataFrame(principalComponents_S2)

Final_Data_S1['labels'] = labels_S1
Final_Data_S2['labels'] = labels_S2


Final_Data_S1 = Final_Data_S1.sample(frac = 1)
Final_Data_S2 = Final_Data_S2.sample(frac = 1)

Source_train = Final_Data_S1.iloc[500:,:]
Source_test = Final_Data_S1.iloc[:500,:]

Target_train = Final_Data_S2.iloc[500:,:]
Target_test = Final_Data_S2.iloc[:500,:]

Source_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_train.csv', index=False)
Source_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Source_test.csv', index=False)
Target_train.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_train.csv', index=False)
Target_test.to_csv('/content/drive/MyDrive/SHOT_IM/data/Target_test.csv', index=False)

#SHOT method

In [41]:
import os
os.chdir('/content/drive/MyDrive/SHOT_IM')


##SHOT-IM

In [42]:
!python uda_digit.py --dset s2m --gpu_id 0 --cls_par 0.0 --output ckps_digits

/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Task: s2m, Iter:423/4230; Accuracy_Source = 71.40%

##Full SHOT

In [43]:
!python uda_digit.py --dset s2m --gpu_id 0 --cls_par 0.1 --output ckps_digits

/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Accuracy = 43.91% -> 38.76%

Task: s2m, Iter:71/2130; Accuracy_Test_1 = 27.80%; f1_score_Test_1 = 0.27335844057586917; f_score_Test_1 = [0.53112033 0.19417476 0.55639098 0.         0.13483146]; confusion_matrix_Test_1 = [[64  1  0 14 14]
 [25 20  0  8 52]
 [ 3 12 37 25 19]
 [ 0 42  0  0 64]
 [56 26  0  0 18]]

Axes(0.125,0.11;0.62x0.77)
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in cu